

#include<stdio.h>

void main() {

	int x = 10;
	//int i = 1;
	fordemo:
		printf("printing........\n");

	for(int i=1; i<=x; i++) {

		goto fordemo;

	}

}
/*
vivek@vivek-HIRAY:~/PPA5/C/Loops/forWhileDOWhileLoop/goto17July(PPA)$ cc gotoState4.c 
vivek@vivek-HIRAY:~/PPA5/C/Loops/forWhileDOWhileLoop/goto17July(PPA)$ ./a.out 
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
printing........
 */
